version: "3.8"
services:
  db_laboratorio:
    image: postgres:16.0
    container_name: db_laboratorio
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
    name: "pgdata"
