services:
  postgres:
    image: postgres:16.0
    container_name: pg_laboratorio
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata:
    name: "pgdata"